// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations via le Session pooler (5432) — le Transaction pooler (6543)
    // ne supporte pas le DDL. Fallback sur DATABASE_URL si DIRECT_URL absent.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
